Fix identifiers "Can't find interface-file" issue
[ 1 of 11] Compiling CSS.Identifiers

/fw/threatlevel-css/CSS/Identifiers.hs:7:16: error:
    • Can't find interface-file declaration for type constructor or class Infinite
        Probable cause: bug in .hi-boot file, or inconsistent .hi file
        Use -ddump-if-trace to get an idea of which file caused the error
    • In the type signature: identifiers :: Infinite Text
  |
7 | identifiers :: Infinite Text
  |                ^^^^^^^^^^^^^

/fw/threatlevel-css/CSS/Identifiers.hs:13:20: error:
    • Can't find interface-file declaration for type constructor or class Infinite
        Probable cause: bug in .hi-boot file, or inconsistent .hi file
        Use -ddump-if-trace to get an idea of which file caused the error
    • In the type signature: identifiersLazy :: Infinite TL.Text
   |
13 | identifiersLazy :: Infinite TL.Text
   |                    ^^^^^^^^^^^^^^^^